server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411   # 和8001 一样,看监控的位置
  sleuth:
    sampler:
      probability: 1   #全部采集

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: springcloud-order-80
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: yss-springcloud
  company.name: www.yss.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
