server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE    # 实现动态路由   分别在8001和8002 上面找 /payment/get/**
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - Cookie=chocolate,duhao # 携带cookie访问
#            - Header=X-Request-Id, \d+  # 如果请求具有名为X-Request-Id其值与\d+正则表达式匹配的标头（即，其值为一个或多个数字），则此路由匹配
#            - Host=**.yss.com

        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE    # 实现动态路由   分别在8001和8002 上面找 /payment/lb/**
#          uri: http://localhost:8002
          predicates:
            Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/    单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka